export const Products = [
  {
    id: 1,
    category: "mobiles",
    title: "Apple iPhone 14",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iPhone 14 (128 GB) - Blue",
    price: 62800,
  },
  {
    id: 5,
    category: "mobiles",
    title: "Apple iPhone 15" ,
    imgSrc: "https://m.media-amazon.com/images/I/71657TiFeHL._SX679_.jpg",
    amazonLink: "https://amzn.to/3EzeQaC",
    description: "Apple iPhone 15 (128 GB) - Black",
    price: 72500,
  },
  {
    id: 7,
    category: "mobiles",
    title: "Nokia G42",
    imgSrc: "https://m.media-amazon.com/images/I/71oIjjNm+nL._SY741_.jpg",
    amazonLink: "https://amzn.to/3ZeNRdY",
    description: "Nokia G42 5G Powered by Snapdragon® 480 Plus 5G| ",
    price: 9999,
  },
  {
    id: 2,
    category: "mobiles",
    title: "Apple iPhone 11",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/44MiYi6",
    description: "Apple iPhone 11 (64GB) - White",
    price: 79999,
  },
  {
    id: 6,
    category: "mobiles",
    title: "SAMSUNG Galaxy S23",
    imgSrc: "https://m.media-amazon.com/images/I/31ducEh481L._SX300_SY300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/3RabsdH",
    description: "SAMSUNG Galaxy S23 FE 5G (Purple 128 GB Storage) (8 GB RAM)",
    price: 45000,
  },
  {
    id: 3,
    category: "mobiles",
    title: "Apple iPhone 13",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3r6XJtv",
    description: "Apple iPhone 13 (128GB) - Blue",
    price: 69999,
  },
  {
    id: 4,
    category: "mobiles",
    title: "Samsung Galaxy M34",
    imgSrc: "https://m.media-amazon.com/images/I/91L9EF-OEGL._AC_UY218_.jpg",
    amazonLink: "https://amzn.to/44JsK4r",
    description: 'Samsung Galaxy M34 5G (Waterfall Blue,6GB,128GB)',
    price: 12999,
  },
  {
    id: 9,
    category: "mobiles",
    title: "Xiaomi 14 ",
    imgSrc: "https://m.media-amazon.com/images/I/41gI9yYlgQL._SX300_SY300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/3Pdsh4F",
    description: "Xiaomi 14 (White, 12GB RAM, 512GB Storage) | 50MP",
    price: 69999,
  },
  {
    id: 8,
    category: "mobiles",
    title: "Redmi 12",
    imgSrc: "https://m.media-amazon.com/images/I/41-2m5Oyv5L._SX300_SY300_QL70_FMwebp_.jpg",
    amazonLink: "https://amzn.to/3r9rvhm",
    description: "Redmi 12 5G Moonstone Silver 6GB RAM 128GB ROM",
    price: 12499,
  },
];
